package com.lyntra.lyntraclans.domain;

public enum ClanPermission {
    CONVIDAR,
    EXPULSAR,
    PROMOVER,
    GERENCIAR_CARGOS,
    BANCO_DEPOSITAR,
    BANCO_SACAR,
    BANCO_VER_SALDO,
    BANCO_GERENCIAR_TAXA,
    GERENCIAR_ALIANCA,
    GERENCIAR_RIVAL,
    BOLETIM,
    UPGRADES,
    ALTERAR_DESCRICAO,
    ALTERAR_HOME,
    DISSOLVER,
    GERENCIAR_CONFIANCA,
    GERENCIAR_GUERRA,
    GERENCIAR_FF_CLA,
    ALTERAR_TAG,
    ACESSAR_BAU
}
